apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  namespace: three-tier-app
  labels:
    app: three-tier-app
data:
  database_url: mongodb-service
  database_port: "27017"
  database_name: admin
  backend_url: backend-service
  backend_port: "8081"
